#pragma once

// ADR-0033: authoritative Tabler glyph catalog for C++-generated RML.
//
// String-literal macros are deliberate: generated markup is assembled from
// adjacent C++ literals, so these keep icon composition allocation-free while
// ensuring that raw PUA character references exist in exactly one file.
// Static .rml documents are verified separately against the vendored font.

#define UI_ICON_DIAGNOSTICS       "&#xea06;"
#define UI_ICON_GRID              "&#xea3b;"
#define UI_ICON_CRATE             "&#xea45;"
#define UI_ICON_BRING_INTO_SCENE  "&#xea5f;"
#define UI_ICON_CHEVRON_RIGHT     "&#xea61;"
#define UI_ICON_CHEVRON_DOWN      "&#xea62;"
#define UI_ICON_COPY              "&#xea7a;"
#define UI_ICON_IMPORT            "&#xea7a;"
#define UI_ICON_GAUGE             "&#xea94;"
#define UI_ICON_TEXT              "&#xea95;"
#define UI_ICON_HIDDEN            "&#xea9a;"
#define UI_ICON_OPEN              "&#xeaad;"
#define UI_ICON_SHARED_INSTANCES  "&#xeade;"
#define UI_ICON_UNLOCKED          "&#xeae1;"
#define UI_ICON_LOCKED            "&#xeae2;"
#define UI_ICON_APPEARANCE        "&#xeb01;"
#define UI_ICON_RENAME            "&#xeb0a;"
#define UI_ICON_ADD               "&#xeb0b;"
#define UI_ICON_SEARCH            "&#xeb1c;"
#define UI_ICON_MOVE_TO_LAYER     "&#xeb2d;"
#define UI_ICON_START_SCENE       "&#xeb2e;"
#define UI_ICON_GENERAL           "&#xeb34;"
#define UI_ICON_DELETE            "&#xeb41;"
#define UI_ICON_SOURCE_LINK       "&#xeb47;"
#define UI_ICON_OBJECT_VARIABLES  "&#xeb4c;"
#define UI_ICON_PLAYER            "&#xeb4d;"
#define UI_ICON_RESET             "&#xeb55;"
#define UI_ICON_EXPAND            "&#xeb5d;"
#define UI_ICON_COLLAPSE          "&#xeb5f;"
#define UI_ICON_UNDO              "&#xeb77;"
#define UI_ICON_COIN              "&#xeb82;"
#define UI_ICON_ENEMY             "&#xeb8e;"
#define UI_ICON_CONTROLLER        "&#xec8e;"
#define UI_ICON_COLLIDER          "&#xeca9;"
#define UI_ICON_GAME_VIEW         "&#xed30;"
#define UI_ICON_PAUSE             "&#xed45;"
#define UI_ICON_PLAY              "&#xed46;"
#define UI_ICON_PREVIOUS          "&#xed48;"
#define UI_ICON_NEXT              "&#xed49;"
#define UI_ICON_DUPLICATE         "&#xedef;"
#define UI_ICON_LAYER_MANAGER     "&#xee9e;"
#define UI_ICON_EMPTY_HIERARCHY   "&#xef94;"
#define UI_ICON_SCRIPTS           "&#xf1b7;"
#define UI_ICON_SPATIAL           "&#xf22f;"
#define UI_ICON_AUDIO             "&#xf2d2;"
#define UI_ICON_OBJECT            "&#xfa97;"
