"""ADR-0027 phase 4 — visual regression for the editor UI.

Renders a set of views with the real editor and compares each against its
committed reference. Two kinds of view:

  * the component gallery — every shared control in every state, in isolation.
    Catches "this control stopped looking right".
  * the real panels, driven by a committed fixture project — Hierarchy with
    layers, a populated Inspector, a Logic Board with rule cards. Catches
    defects of *composition* the gallery structurally cannot see: the key
    picker whose hover rule leaked the search panel's layout lived here, and
    was reported from the UI rather than by any test.

  python scripts/check_ui_gallery.py            # compare every view
  python scripts/check_ui_gallery.py --update   # accept the current rendering
  python scripts/check_ui_gallery.py --only logic

Exit code 0 when every view matches, 1 otherwise (the actual and diff images
are written next to the reference for inspection).
"""
import argparse
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EXE = ROOT / "build" / "src" / "artcade-editor-native.exe"
REFDIR = ROOT / "tests" / "reference"
FIXTURE = REFDIR / "visual-fixture.artcade"

# name -> extra CLI arguments. The fixture is regenerated by
# `artcade-editor-native --write-fixture` (src/editor-native/app/visual_fixture.cpp),
# so it stays readable and reviewable instead of being an opaque blob.
VIEWS = {
    "gallery": ["--shot-gallery"],
    "scene":   ["--shot-project", str(FIXTURE), "--shot-entity", "0"],
    "logic":   ["--shot-project", str(FIXTURE), "--shot-entity", "0", "--shot-logic"],
    "anim":    ["--shot-project", str(FIXTURE), "--shot-anim"],
    "tileset": ["--shot-project", str(FIXTURE), "--shot-tileset"],
    # ADR-0029: the completion list is the whole discovery surface now that the
    # node palette is gone, and it only exists while a field has focus — which
    # no static capture would otherwise reach.
    # Address form: ruleId|actionId|target|blockIndex|property|component
    # (per-action ids from ADR action modes; first Place action is action-1).
    "expression": ["--shot-project", str(FIXTURE), "--shot-entity", "0", "--shot-logic",
                   "--shot-expression", "rule-place|action-1|a|0|position|x",
                   "--shot-expression-text", "ra"],
}

# The capture is a real GPU render, so a handful of pixels may differ by a
# quantisation step between drivers. Anything a human would notice — a colour
# role, a lost state, a reflow — moves far more than this.
CHANNEL_TOLERANCE = 8
MAX_DIFFERING_PIXELS = 200

# The status bar prints the pointer's world position, which depends on where
# the physical mouse happens to sit when the capture runs — it made the scene
# view differ from a reference generated seconds earlier. The bottom strip is
# therefore excluded from the comparison; everything above it, including the
# whole workspace, is still diffed.
IGNORE_BOTTOM_PX = 26


def render(view: str, target: pathlib.Path) -> None:
    if not EXE.exists():
        sys.exit(f"editor not built: {EXE}\nbuild artcade-editor-native first")
    if view != "gallery" and not FIXTURE.exists():
        sys.exit(f"fixture missing: {FIXTURE}\n"
                 f"regenerate it with: {EXE.name} --write-fixture {FIXTURE}")
    target.parent.mkdir(parents=True, exist_ok=True)
    # raylib's TakeScreenshot writes to the working directory under the given
    # name, ignoring any directory part — so capture beside the repo root and
    # move the file where it belongs.
    scratch = ROOT / "ui-capture.png"
    if scratch.exists():
        scratch.unlink()
    result = subprocess.run(
        [str(EXE), "--shot", scratch.name, *VIEWS[view]],
        cwd=ROOT, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(
            f"editor failed for '{view}' with exit code "
            f"{result.returncode}:\n"
            + (result.stdout or "")[-2000:]
            + (result.stderr or "")[-2000:]
        )
    if not scratch.exists():
        sys.exit(f"capture failed for '{view}':\n"
                 + (result.stdout or "")[-2000:]
                 + (result.stderr or "")[-2000:])
    if target.exists():
        target.unlink()
    scratch.replace(target)


def compare(view: str, reference: pathlib.Path, actual: pathlib.Path) -> int:
    from PIL import Image, ImageChops

    ref = Image.open(reference).convert("RGB")
    cur = Image.open(actual).convert("RGB")
    if ref.size != cur.size:
        print(f"FAIL [{view}] size changed: reference {ref.size} vs actual {cur.size}")
        print("      a layout change this large is never accidental — review it")
        return 1

    diff = ImageChops.difference(ref, cur)
    limit = diff.height - IGNORE_BOTTOM_PX
    differing = [
        (x, y)
        for y in range(limit) for x in range(diff.width)
        if max(diff.getpixel((x, y))) > CHANNEL_TOLERANCE
    ]
    if len(differing) <= MAX_DIFFERING_PIXELS:
        print(f"OK   [{view}] matches ({len(differing)} px differ, "
              f"tolerated {MAX_DIFFERING_PIXELS})")
        return 0

    xs = [p[0] for p in differing]
    ys = [p[1] for p in differing]
    diff_path = REFDIR / f"ui-{view}.diff.png"
    diff.save(diff_path)
    print(f"FAIL [{view}] {len(differing)} pixels differ from the reference")
    print(f"     bounding box x {min(xs)}–{max(xs)}, y {min(ys)}–{max(ys)}")
    print(f"     actual: {actual}")
    print(f"     diff:   {diff_path}")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--update", action="store_true",
                        help="replace the references with the current rendering")
    parser.add_argument("--only", choices=sorted(VIEWS),
                        help="restrict to a single view")
    args = parser.parse_args()

    try:
        import PIL  # noqa: F401
    except ImportError:
        sys.exit("Pillow is required: pip install pillow")

    views = [args.only] if args.only else list(VIEWS)
    failures = 0
    for view in views:
        reference = REFDIR / f"ui-{view}.png"
        if args.update:
            render(view, reference)
            print(f"reference updated: {reference}")
            continue
        if not reference.exists():
            print(f"FAIL [{view}] no reference yet — create it with --update")
            failures += 1
            continue
        actual = REFDIR / f"ui-{view}.actual.png"
        render(view, actual)
        failures += compare(view, reference, actual)

    if failures and not args.update:
        print("\nif the changes are intended: "
              "python scripts/check_ui_gallery.py --update")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
